community/base/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.homepage, name='home'),
]

community/community/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^servers/', include('stats.urls')),
    url(r'^suggestions/', include('suggestions.urls', namespace='suggestions')),
    url(r'^forum/', include('forum.urls', namespace='forum')),
    url(r'^auth/steam/', include('steamauthprovider.urls')),
    url(r'^', include('base.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        url(r'^admin/uwsgi/', include('django_uwsgi.urls'))
    ] + urlpatterns

community/forum/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^category/(?P<slug>[-\w]+)/$', views.view_category, name='view_category'),
    url(r'^forum/(?P<slug>[-\w]+)/$', views.view_forum, name='view_forum'),
    url(r'^topic/(?P<slug>[-\w]+)/$', views.view_topic, name='view_topic'),
    url(r'^post/(?P<slug>[-\w]+)/$', views.view_post, name='view_post'),
]

community/base/models.py
from django.db import models
from ordered_model.models import OrderedModel
from django.contrib.postgres.fields import JSONField
from simple_history.models import HistoricalRecords
from django.utils import timezone
from django.conf import settings
from django.core.cache import cache
from django.core.validators import *
from django.contrib.auth.models import Permission
from .util import message_metadata_factory, site_setting_ensure
from django.core.exceptions import PermissionDenied
import re

site_setting_ensure("DISABLED", "false", "If true website is only accessible to Super Admins")
site_setting_ensure("AUTHOR", "Doldol @ http://steamcommunity.com/id/Doldol/", "The Main Developer, Doldol @ http://steamcommunity.com/id/Doldol/")
site_setting_ensure("NOTICE", "", "Notice displayed at all times")
site_setting_ensure("BASE_TITLE", "The Elevated Gaming Network", "The Base title of the whole site")
site_setting_ensure("META_KEYWORDS", "", "Meta header keywords")
site_setting_ensure("META_DESCRIPTION", "", "Meta header site description")


class MessageMetaField(JSONField):
	description = "Meta data for message text"

	def __init__(self, *args, **kwargs):
		kwargs['default'] = message_metadata_factory
		super().__init__(*args, **kwargs)

	@property
	def hashtags(self):#are search tags
		return self["hashtags"]

	@hashtags.setter
	def hashtags(self, value):
		self["hashtags"] = value

	@property
	def user_mentions(self):
		return self["user_mentions"]

	@user_mentions.setter
	def user_mentions(self, value):
		self["user_mentions"] = value

	@property
	def group_mentions(self):
		return self["group_mentions"]

	@group_mentions.setter
	def group_mentions(self, value):
		self["group_mentions"] = value


class BBCodeField(JSONField):
	pass

class BaseMessage(models.Model):
	title = models.CharField(max_length=200)
	metadata = MessageMetaField()

	class Meta:
		abstract=True

class Section(models.Model):
	name = models.CharField(max_length=200)

class Article(models.Model):
	subject = models.CharField(max_length=200)
	sections = models.ManyToManyField(Section, through='SectionArticle')

class SectionArticle(OrderedModel):
	section = models.ForeignKey(Section)
	article = models.ForeignKey(Article)
	order_with_respect_to = 'section'

	class Meta(OrderedModel.Meta):
		pass

class SiteSetting(models.Model):
	name = models.CharField(max_length=100, unique=True)
	value = JSONField()
	description = models.TextField(max_length=1000, blank=True, null=True)

	def __str__(self):
		return self.name

	@property
	def value_preview(self):
		return str(self.value)[:25]

	def save(self, *args, **kwargs):
		cache.set("setting-{0}".format(self.name), self.value)
		super().save(*args, **kwargs)

	@classmethod
	def get_setting(clas, name):
		value = cache.get("setting-{0}".format(name))
		if not value:
			value = clas.objects.get(name=name).value
			cache.set("setting-{0}".format(name), value)
		return value

	@classmethod
	def ensure(clas, name, default=None, description=None):
		if not cache.get("setting-{0}".format(name)):
			if not clas.objects.filter(name=name).exists():
				setting = clas(name=name, value=default,  description=description)
				setting.save()

class SideBarEntry(OrderedModel):
	name = models.CharField(max_length=100)
	location = models.CharField(max_length=500, blank=True, null=True)
	parent = models.ForeignKey('self', related_name="children", blank=True, null=True)
	faicon = models.CharField(max_length=20, blank=True, null=True)
	styling = models.CharField(max_length=255, blank=True, null=True)
	order_with_respect_to = 'parent'

	def __str__(self):
		return "{0}.{1}".format(self.parent, self.name)


class GenericPostsByViewAndPos(models.Model):
	view_object_name = models.CharField(max_length=100, unique=True) # name of view object
	position = models.PositiveSmallIntegerField()

	def __str__(self):
		return "GenericPosView.{0}".format(self.id)

	class Meta:
		unique_together = (("view_object_name", "position"),)


class GenericPost(models.Model):
	title = models.CharField(max_length=100)
	created = models.DateTimeField(verbose_name='Date created', default=timezone.now)
	author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='generic_posts_from')
	changed_by = models.ForeignKey('auth.User')
	message_html =  models.TextField(verbose_name='Message in HTML', unique=True, max_length=50000)
	message = models.TextField(verbose_name='Message in BBCode', unique=True, max_length=40000)
	parent_views = models.ManyToManyField(GenericPostsByViewAndPos, through="GenericPostsViewsThroughModel")
	_message_metadata = JSONField(default=message_metadata_factory)

	history = HistoricalRecords()

	def __str__(self):
		return "{0}.{1}".format(self.id, self.title)

	def save(self, *args, **kwargs):
		# calc metadata
		super().save(*args, **kwargs)

	@property
	def _history_user(self):
		return self.changed_by

	@_history_user.setter
	def _history_user(self, value):
		self.changed_by = value

	@property
	def hashtags(self):
		return self._message_metadata["hashtags"]

	@hashtags.setter
	def hashtags(self, value):
		self._message_metadata["hashtags"] = value

	@property
	def user_mentions(self):
		return self._message_metadata["user_mentions"]

	@user_mentions.setter
	def user_mentions(self, value):
		self._message_metadata["user_mentions"] = value

	@property
	def group_mentions(self):
		return self._message_metadata["group_mentions"]

	@group_mentions.setter
	def group_mentions(self, value):
		self._message_metadata["group_mentions"] = value

class GenericPostsViewsThroughModel(OrderedModel):
	view = models.ForeignKey(GenericPostsByViewAndPos)
	post = models.ForeignKey(GenericPost)
	order_with_respect_to = 'view'

	class Meta:
		ordering = ("view", 'order')

community/base/views.py
from django.shortcuts import render

# Create your views here.

def homepage(request):
	context = {
		'Test': 1,
	}

	return render(request, 'base/homepage.html', context)

community/base/templates/base.html
{% load static %}
{% load i18n %}

{% load base_tags %}

<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=12.0, minimum-scale=.05, user-scalable=yes">
	<meta name="description" content="{% site_setting 'META_DESCRIPTION' %}" />
	<meta name="keywords" content="{% site_setting 'META_KEYWORDS' %}" />
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="author" content="{% site_setting 'AUTHOR' %}">

	<link rel="preload" as="font" href="{% static "fonts/fontawesome-webfont.woff2" %}">
	<link rel="preload" as="font" href="{% static "fonts/glyphicons-halflings-regular.woff2" %}">
	<link rel="preload" as="font" href="{% static "fonts/CGFLocustResistance.woff" %}">    
	<link rel="preload" as="image" href="{% static "img/header_txt.svg" %}">

	<title>{% block title %}{% endblock %}{% site_setting 'BASE_TITLE' %}</title>

	<!-- Bootstrap Core CSS -->
	<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
	<link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet">

	<!-- Custom CSS -->
	<link href="{% static "css/bootstrap-theme.css" %}" rel="stylesheet">
	<link href="{% static "css/site-style-base.css" %}" rel="stylesheet">

	{% load staticfiles %}

	<link rel="shortcut icon" href="{% static "favicon.ico" %}" type="image/png" />

	<style type="text/css">
	.navbar-centered {
	  display: flex;
	  justify-content: center;
	  position: absolute;
	  height: 100%;
	  width: 100%;
	  left: 0;
	  top: 0;
	}
	.navbar-centered-sub {
	  display: flex;
	  align-items: center;
	}
	.navbar .navbar-nav>li>a {
    border-left: 1px solid rgba(255,255,255,0.1);
    border-right: 1px solid rgba(255,255,255,0.1);
	}
	.navbar-toggle {
	  z-index: 1;
	}
	.navbar-centered>ul>li>a {
	margin-left: 15px;
    margin-right: 15px;
	}
	</style>

	{% block beforebody %}{% endblock beforebody %}

</head>





<body>

	<div id="wrapper">
		<!-- Left Sidebar -->
		<div id="left-sidebar-wrapper">
			<ul class="sidebar-nav">
				<li class="sidebar-brand">
				 
				</li>
				{% block menu %}
				<li>
					<a id="navhome" href="{% url 'home' %}">
						<span class="fa-stack fa-lg pull-left">
							<i class="fa fa-home fa-stack-1x fa-fw"></i>
						</span>
						{% trans "Home" %}
					</a>
				</li>
				<li>
					<a id="navgs" href="{% url 'server-list' %}">
						<span class="fa-stack fa-lg pull-left">
							<i class="fa fa-server fa-stack-1x fa-fw"></i>
						</span>
						{% trans "Game Servers" %}
					</a>
				</li>
				<li>
					<a id="navgs" href="{% url 'server-list' %}">
						<span class="fa-stack fa-lg pull-left">
							<i class="fa fa-server fa-stack-1x fa-fw"></i>
						</span>
						{% trans "Item Shop" %}
					</a>
				</li>
				<li>
					<a id="navgs" href="{% url 'server-list' %}">
						<span class="fa-stack fa-lg pull-left">
							<i class="fa fa-server fa-stack-1x fa-fw"></i>
						</span>
						{% trans "Video Chat/Share" %}
					</a>
				</li>
				<li>
					<a id="navgs" href="{% url 'server-list' %}">
						<span class="fa-stack fa-lg pull-left">
							<i class="fa fa-server fa-stack-1x fa-fw"></i>
						</span>
						{% trans "Bans/Restrictions" %}
					</a>
				</li>
				<li>
					<a data-toggle="collapse" href="#dashboard" aria-expanded="false">                        
						<span class="fa-stack fa-lg pull-left">
							<i class="fa fa-commenting fa-stack-1x fa-fw"></i>
						</span>
						{% trans "Forum" %}<i class="fa fa-caret-down" aria-hidden="true"></i>
					</a>
					<div class="collapse sub-bar" id="dashboard">
						<a id="navindex" href="{% url 'forum:index' %}">{% trans "Index" %}</a>
						<a href="">{% trans "Show recent posts" %}</a>
						<a href="">{% trans "Show unanswered posts" %}</a>
						{% if user.is_authenticated %}
							<a href="">{% trans "Show new posts since last visit" %}</a>
							<a href="">{% trans "Mark all topics as read" %}</a>
							<a href="">{% trans "Show your subscribed topics" %}</a>
							<a href="">{% trans "Show your" %}&nbsp;{% trans "topics" %}</a>
							<a href="">{% trans "Show your" %}&nbsp;{% trans "posts" %}</a>
						{% endif %}
					</div>
				</li>
				<li>
					 <a id="navuserlist" href="">
						<span class="fa-stack fa-lg pull-left">
							<i class="fa fa-users fa-stack-1x fa-fw"></i>
						</span>
					   {% trans "User list" %}
					</a>
				</li>
				<li>
					 <a id="navsuggestions" href="{% url 'suggestions:index' %}">
						<span class="fa-stack fa-lg pull-left">
							<i class="fa fa-folder-open fa-stack-1x fa-fw"></i>
						</span>
					   {% trans "Suggestions" %}
					</a>
				</li>
				{% if user.is_authenticated %}
					<li>
						<a id="navprofile" href="">
							<span class="fa-stack fa-lg pull-left">
								<i class="fa fa-user fa-stack-1x fa-fw"></i>
							</span>
							{% trans "Profile" %}
						</a>
					</li>
					<li>
						<a id="navpm" href="">
							<span class="fa-stack fa-lg pull-left">
								<i class="fa fa-comments-o fa-stack-1x fa-fw"></i>
								</span>
							{% trans "PM" %}
						</a>
					</li>
				{% endif %}
				{% endblock %}
			</ul>
		</div>

		<!-- Right Sidebar -->
		<div id="right-sidebar-wrapper">
			<ul class="sidebar-nav">
				<li class="sidebar-brand">
					
				</li>
				{% if user.is_authenticated %}
					<li>
						<a id="navlogout" href="{% url 'steamlogout' %}?next={{ request.path }}">
							<span class="fa-stack fa-lg pull-left">
								<i class="fa fa-sign-out fa-stack-1x fa-fw" aria-hidden="true"></i>
							</span>
							{% trans "Log out" %}
						</a>
					</li>
				{% else %}
					<li style="background-color: rgb(155,0,0)">
						<a id="navlogin" href="{% url 'steamlogin' %}?next={{ request.path }}">
							<span class="fa-stack fa-lg pull-left">
								<i class="fa fa-sign-in fa-stack-1x fa-fw" aria-hidden="true"></i>
							</span>
							{% trans "Log in" %}
						</a>
					</li>
				{% endif %}
				<li>
					<a id="navsearch" href="">
						<span class="fa-stack fa-lg pull-left">
							<i class="fa fa-search fa-stack-1x fa-fw"></i>
						</span>
						{% trans "Search" %}
					</a>
				</li>
				<li>
					<a data-toggle="collapse" href="#recent-search" aria-expanded="false">
						<span class="fa-stack fa-lg pull-left">
							<i class="fa fa-search fa-stack-1x fa-fw"></i>
						</span>
						Recent Search <span class="caret"></span>
					</a>
					
					<div class="collapse sub-bar" id="recent-search">
						<a href="#">Keyword 1</a>
						<a href="#">Keyword 2</a>
						<a href="#">Keyword 3</a>
						<a href="#">Keyword 4</a>
					</div>
				</li>
				<li>
					<a id="navadmin" href="{% url 'admin:index' %}">
						<span class="fa-stack fa-lg pull-left">
							<i class="fa fa-unlock-alt fa-stack-1x fa-fw"></i>
						</span>
						{% trans "Administration" %}
					</a>
				</li>
		</div>

		<div id="page-vertical-wrapper">
			<header>
				<span>
					<object data="{% static "img/header_txt.svg" %}" type="image/svg+xml">
						<h1>The Unforgotten</h1>
					</object>
				</span>
			</header>

			<!-- Head -->
			<div style="min-height:204px">
			<div id="page-head-wrapper" data-spy="affix" data-offset-top="150">

				<div></div>

				<nav class="navbar navbar-mystyle navbar-top">
					<div class="navbar-header">
					  <button type="button" class="navbar-toggle collapsed btn btn-default" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<i class="fa fa-ellipsis-h" aria-hidden="true"></i>
					  </button>
					</div>

					<div class="navbar-centered hidden-lg hidden-md hidden-sm">
					  <ul class="nav navbar-nav">
						<li><a href="#left-menu-toggle" class="btn btn-link btn-md left-menu-toggle"><span class="fa fa-align-left" aria-hidden="true"></span></a></li>
					  </ul>
					  <ul class="nav navbar-nav">
						<li><a href="#right-menu-toggle" class="btn btn-link btn-md right-menu-toggle"><span class="fa fa-align-right" aria-hidden="true"></span></a></li>
					  </ul>
					</div>

					<div id="navbar" class="navbar-collapse collapse">
					  <ul class="nav navbar-nav navbar-left hidden-xs">
						<li><a href="#left-menu-toggle" class="btn btn-link btn-md left-menu-toggle" style="margin-right: 15px;"><span class="fa fa-align-left" aria-hidden="true"></span></a></li>
					  </ul>
					  <ul class="nav navbar-nav navbar-right hidden-xs">
						<li><a href="#right-menu-toggle" class="btn btn-link btn-md right-menu-toggle" style="margin-left: 15px;"><span class="fa fa-align-right" aria-hidden="true"></span></a></li>
					  </ul>
					  <ul class="nav navbar-nav">
					  	<!-- User Favorites go here -->
					  </ul>
					</div>
				</nav>

			</div>
			</div>

			<!-- Page Content -->
			<div id="page-content-wrapper">

				<div class="container-fluid">
					<div id="django-msg-wrapper">
					{% include 'header.html' %}
					{% block messages %}
						{% for message in messages %}
							<div class="alert alert-dismissible alert-{% if message.tags %}{{ message.tags }}{% else %}info{% endif %}">
								<button type="button" class="close" data-dismiss="alert">&times;</button>		 
								<h4>{% trans "Notice" %}</h4>
								<p>{{ message }}</p>
							</div>
						{% endfor %}
					{% endblock messages %}
					</div>

					{% block pre_content %}{% endblock %}
					{% block content %}{% endblock %}
					{% block post_content %}{% endblock %}

					<div class="row">
						<div class="col-sm-4">
							<p class="text-center">Website by <a href="http://steamcommunity.com/profiles/76561197988220707/">Doldol</a></p>
						</div>
						<div class="col-sm-4">
							<p class="text-center">{% block controls %}{% endblock controls %}</p>
						</div>
						<div class="col-sm-4">
							<p class="text-center">Powered by Django</p>
						</div>
					</div>
				</div>

			</div>

		</div>
			<!-- /#page-content-wrapper -->
	</div>
	<!-- /#wrapper -->

	<!-- 3rd Party Libs -->
	{% block afterbody %}{% endblock afterbody %}

	<script src="{% static "js/jquery-3.1.0.min.js" %}"></script>	
	<script src="{% static "js/jquery.mobile.touch.min.js" %}"></script>
	<script src="{% static "js/bootstrap-3.3.7.min.js" %}"></script>
	<script src="{% static "js/ResizeSensor.js" %}"></script>

	<script type="text/javascript">
		var STATIC_URL = "{{ STATIC_URL }}";
	</script>

	<!-- Script -->
	<script>
	$(document).ready(function(){
		$('[data-toggle="tooltip"]').tooltip();   
	});

	function collapse_sidebar(side) {
	    $("#wrapper").prop("classList").remove(side+"-toggled");
	    $('#'+side+'-sidebar-wrapper .collapse').collapse('hide');

	    localStorage.setItem("sidebar-"+side+"-toggled", "0");
	}

	function expand_sidebar(side) {
	    $("#wrapper").prop("classList").add(side+"-toggled");

	    localStorage.setItem("sidebar-"+side+"-toggled", "1");
	}

	var mq_min_768 = window.matchMedia( "(min-width: 768px)" );

	if (mq_min_768.matches) {
		if (localStorage.getItem("sidebar-left-toggled") == "1") {
			expand_sidebar("left");
		}

		if (localStorage.getItem("sidebar-right-toggled") == "1") {
			expand_sidebar("right");
		}
	}
	
	$(".collapse").on('show.bs.collapse', function(){
		if ($(this).closest('#left-sidebar-wrapper').length) {
			expand_sidebar("left");
		} else if ($(this).closest('#right-sidebar-wrapper').length) {
			expand_sidebar("right");
		}
	});
	
	$("#right-sidebar-wrapper").on("swipeleft",function(){
		expand_sidebar("right");
	});
	$("#right-sidebar-wrapper").on("swiperight",function(){
		collapse_sidebar("right")
	});

	$("#left-sidebar-wrapper").on("swiperight",function(){
		expand_sidebar("left");
	});
	$("#left-sidebar-wrapper").on("swipeleft",function(){
		collapse_sidebar("left");
	});

	$(".left-menu-toggle").click(function(e) {
		e.preventDefault();
		if ($("#wrapper").hasClass("left-toggled")) {
			collapse_sidebar("left");
		} else {
			expand_sidebar("left");
		}
	});

	$(".right-menu-toggle").click(function(e) {
		e.preventDefault();
		if ($("#wrapper").hasClass("right-toggled")) {
			collapse_sidebar("right");
		} else {
			expand_sidebar("right");
		}
	});

	var $affixElement = $('div[data-spy="affix"]');
	new ResizeSensor($affixElement.parent(), function() {
		$affixElement.width($affixElement.parent().width());
	});

	$(window).resize(function () {
		var $affixElement = $('div[data-spy="affix"]');
		$affixElement.width($affixElement.parent().width());
	});

	$(window).scroll(function(){
		var scrlOff = $(window).scrollTop();
		if (scrlOff > 150) {
			$("#wrapper").css("background-position", "center -150px");
			$("#page-content-wrapper").css("background-position", "center -150px");
		} else {
			$("#page-content-wrapper").css("background-position", "center -"+scrlOff.toString()+"px");
			$("#wrapper").css("background-position", "center -"+scrlOff.toString()+"px");
		}
	});
	</script>

	{% block afterscript %}{% endblock afterscript %}

</body>

</html>

community/base/templates/header.html
{% load i18n %}
{% load base_tags %}

{% site_setting 'NOTICE' as site_setting_NOTICE %}

{% if user.is_superuser and reports %}
	<div class="alert alert-dismissible alert-warning">
		<button type="button" class="close" data-dismiss="alert">&times;</button>		  
		<strong><a href="{% url 'admin:index' %}">{% trans "There are new reports" %} ({{ new_reports }})</a></strong>	  
	</div>
{% endif %}

{% if site_setting_NOTICE %}
	<div class="alert alert-dismissible alert-info">
		<button type="button" class="close" data-dismiss="alert">&times;</button>		 
		<h4>{% trans "Notice" %}</h4>
		<p>{{ site_setting_NOTICE }}</p>
	</div>
{% endif %}