community/base/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.homepage, name='home'),
]

community/community/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^servers/', include('stats.urls')),
    url(r'^suggestions/', include('suggestions.urls', namespace='suggestions')),
    url(r'^forum/', include('forum.urls', namespace='forum')),
    url(r'^auth/steam/', include('steamauthprovider.urls')),
    url(r'^', include('base.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        url(r'^admin/uwsgi/', include('django_uwsgi.urls'))
    ] + urlpatterns

community/suggestions/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^add/', views.add_suggestion, name='add_suggestion'),
	url(r'^filtered/$', views.filtered_overview, name='filtered_overview'),  
	url(r'^view/(?P<object_id>\d+)/$', views.view_suggestion, name='view_suggestion_id'),
	url(r'^view/(?P<slug>[-\w]+)/$', views.view_suggestion, name='view_suggestion_slug'),
	url(r'^edit/(?P<object_id>\d+)/$', views.edit_suggestion, name='edit_suggestion_id'),
	url(r'^edit/(?P<slug>[-\w]+)/$', views.edit_suggestion, name='edit_suggestion_slug'),
	url(r'^post_vote/', views.post_vote, name='post_vote'),
]

community/suggestions/models.py
from django.db import models
from django.conf import settings
from django.template.defaultfilters import slugify
from django.utils import timezone
from django.utils.html import conditional_escape
from django.utils.translation import ugettext_lazy as _
from django.utils.functional import cached_property
from django.urls import reverse # v10

from base.util import convert_text_to_html, site_settings,  site_setting_ensure

site_setting_ensure("MARKUP", "bbcode", "Markup used for user content")
site_setting_ensure("SUGGESTIONS_DEFAULT_VALUE", "New", "Default Status for suggestions.")
site_setting_ensure("SUGGESTIONS_ARCHIVED_VALUE", ["Completed","Rejected"], "Satuses that count as archived.")

class SuggestionCategory(models.Model):
	value = models.TextField(_('Value'), max_length=25)

	class Meta:
		ordering = ('value',)
		verbose_name = "Category"
		verbose_name_plural = "Categories"

	def __str__(self):
		return self.value

	__unicode__ = __str__

class SuggestionStatus(models.Model):
	value = models.TextField(_('Value'), max_length=25)
	value_html = models.TextField(_('HTML Value'), max_length=250)

	class Meta:
		ordering = ('value',)
		verbose_name = "Status"
		verbose_name_plural = "Statuses"

	def __str__(self):
		return self.value

	__unicode__ = __str__

class Suggestion(models.Model):
	slug = models.SlugField(unique=True, blank=True)
	from_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='suggestions_from', verbose_name=_('From'))
	time = models.DateTimeField(_('Time'), default=timezone.now)
	title = models.CharField(_('Title'), unique=True, max_length=100)
	message = models.TextField(_('Message'), unique=True, max_length=40000)
	message_html = models.TextField(_('Message HTML'), unique=True, max_length=50000, blank=True)
	status = models.ForeignKey(SuggestionStatus)
	categories = models.ManyToManyField(SuggestionCategory)

	@property
	def get_rating(self):
		return self.votes.all().aggregate(models.Sum('value'))['value__sum']

	@classmethod
	def get_all_with_rating(self):
		return Suggestion.objects.all().annotate(rating=models.Sum('votes__value'))

	@classmethod
	def get_filtered_with_rating(self, filter_args, exclude=False):
		if exclude:
			return Suggestion.objects.exclude(**filter_args).annotate(rating=models.Sum('votes__value'))
		else:
			return Suggestion.objects.filter(**filter_args).annotate(rating=models.Sum('votes__value'))

	@cached_property
	def get_absolute_url(self):
		return reverse('suggestions:view_suggestion_slug', kwargs={'slug': self.slug})

	def save(self, *args, **kwargs):
		if not self.id:
			# Newly created
			if not self.slug:
				self.slug = slugify(self.title)

		if self.message != self.__original_message:
			self.message_html = convert_text_to_html(self.message, site_settings.MARKUP)
#			if forum_settings.SMILES_SUPPORT and self.from_user.forum_profile.show_smilies:
#				self.message_html = smiles(self.message_html)

		super().save(*args, **kwargs)
		self.__original_message = self.message

	class Meta:
		ordering = ('time', "status", "title")
		verbose_name = _('Suggestion')
		verbose_name_plural = _('Suggestions')
		permissions = (
			('post_suggestion', 'Submit Suggestion'),
			('edit_suggestion', 'Edit own Suggestion'),
			('post_vote', 'Vote on Suggestions'),
			('edit_vote', 'Edit own vote'),
			('post_comment', 'Submit Comment'),
			('edit_comment', 'Edit own Comment'),
			('moderate_suggestion', 'Edit and delete other Suggestion'),
			('moderate_comment', 'Edit and delete other comment'),
			('devupdate_suggestion', 'Change others suggestion status (for developers)'),
		)

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.__original_message = self.message

	def __str__(self):
		return self.slug

	__unicode__ = __str__


class SuggestionComment(models.Model):
	from_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='suggestion_comments_from', verbose_name=_('From'))
	for_suggestion = models.ForeignKey(Suggestion, related_name='comments', verbose_name=_('To'))
	time = models.DateTimeField(_('Time'), default=timezone.now)
	body = models.TextField(_('Body'))
	body_html = models.TextField(_('HTML version'))

	def save(self, force_insert=False, force_update=False, *args, **kwargs):
		if self.body != self.__original_body:
			self.body_html = convert_text_to_html(self.body, site_settings.MARKUP)
#			if forum_settings.SMILES_SUPPORT and self.from_user.forum_profile.show_smilies:
#				self.body_html = smiles(self.body_html)

		super().save(force_insert, force_update, *args, **kwargs)
		self.__original_body = self.body

	class Meta:
		verbose_name = "Comment"
		verbose_name_plural = "Comments"

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.__original_body = self.body

	def __str__(self):
		return "SuggestionComment.{0}".format(self.id)

	__unicode__ = __str__


class SuggestionVote(models.Model):
	VALUE_CHOICES = (
		(-1, 'Down'),
		(1, 'Up'),	)
	from_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='votes_from', verbose_name=_('From'))
	for_suggestion = models.ForeignKey(Suggestion, related_name='votes', verbose_name=_('For'))
	value = models.SmallIntegerField(verbose_name=_('Vote Value'), choices=VALUE_CHOICES)
	time = models.DateTimeField(_('Time'), default=timezone.now)

	class Meta:
		verbose_name = "Vote"
		verbose_name_plural = "Votes"
		unique_together = (('from_user', 'for_suggestion'),)

	def __str__(self):
		return "SuggestionVote.{0}".format(self.id)

	__unicode__ = __str__

community/suggestions/forms.py
from .models import Suggestion, SuggestionStatus

from django import forms

from base.util import site_setting_ensure, site_settings
from base.models import SiteSetting#, SuggestionCategory
from django.contrib.auth import get_user_model





# Create the form class.
class AddSuggestionForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		self.user = kwargs.pop('user', None)
		super().__init__(*args, **kwargs)

	def save(self, *args, **kwargs):
		x = super().save(commit=False)
		x.from_user = get_user_model().objects.get(id=self.user)
		x.status = SuggestionStatus.objects.get(value=site_settings.SUGGESTIONS_DEFAULT_VALUE)
		x.save()
		return x

	class Meta:
		model = Suggestion
		fields = ('title', 'message', 'categories')


# usage: form = AddSuggestionForm(user=request.user)

community/suggestions/views.py
from .forms import AddSuggestionForm
from .models import SuggestionVote, Suggestion
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.http import Http404, HttpResponseRedirect
from django.utils import timezone
from django.db import transaction

from base.util import get_page, get_preferred_name_by_instance, site_settings

import json


#TODO implement comments, all templates, index
JSON_POST_TUPLE = (-1,1)


@login_required
def add_suggestion(request):
	form_kwargs = {"user": request.user.id}

	if request.method == 'POST':
		form = AddSuggestionForm(request.POST, **form_kwargs)
		if form.is_valid():
			suggestion = form.save()
			form.save_m2m()
			messages.success(request, "Suggestion Saved")
			return HttpResponseRedirect(suggestion.get_absolute_url)
		else:
			raise Exception("Form Not Valid")
	else:
		form = AddSuggestionForm(**form_kwargs)

	context = {
		'form': form,
		'form_url': request.path,
	}
	return render(request, 'suggestions/add.html', context)

def view_suggestion(request, slug=None, object_id=None):
	if slug:
		suggestion = get_object_or_404(Suggestion, slug=slug)
	elif object_id:
		suggestion = get_object_or_404(Suggestion, id=object_id)
	else:
		raise Http404(_("Suggestion does not exist"))

	try:
		if not request.user.is_authenticated():
			raise ObjectDoesNotExist
		vote = request.user.votes_from.get(for_suggestion=suggestion).value
	except ObjectDoesNotExist:
		vote = 0

	context = {
		'suggestion': suggestion,
		'vote_up_active': True if vote == 1 else False,
		'vote_down_active': True if vote == -1 else False,
	}

	return render(request, 'suggestions/view.html', context)

@login_required
def edit_suggestion(request, slug=None, object_id=None):
	raise NotImplementedError("You are in the right place at the wrong time, please come back in the future.")

def index(request):
	suggestions = Suggestion.get_filtered_with_rating({"status__value__in": site_settings.SUGGESTIONS_ARCHIVED_VALUE}, exclude=True).select_related('status').prefetch_related('categories').order_by('-time')

	context = {
		'suggestions_page': get_page(suggestions, request, 25),
	}
	return render(request, 'suggestions/index.html', context)

def filtered_overview(request):
	query_dict = {}
	in_all_cats = request.GET.getlist('all', False)
	categories = request.GET.getlist('c', None)
	status = request.GET.getlist('s', None)

	if categories:
		query_dict["status__value__in"] = status
	if status:
		query_dict["categories__value__in"] = status

	suggestions = Suggestion.get_filtered_with_rating(query_dict)

	if in_all_cats:
		suggestions = suggestions.annotate(num_tags=Count('tags')).filter(num_tags=len(categories))

	suggestions = suggestions.select_related('status').prefetch_related('categories').order_by('-time')

	context = {
		'suggestions_page': get_page(suggestions, request, 25),
	}
	return render(request, 'suggestions/filtered.html', context)	

def post_vote(request):
	if not request.user.is_authenticated(): #has perms?
		response_data = {"ERROR": "No Permission"}
	elif request.method == 'POST':
		for_suggestion = int(request.POST.get('for_suggestion'))
		vote_data = int(request.POST.get('vote_data'))
		if vote_data not in JSON_POST_TUPLE:
			response_data = {"ERROR": "Invalid Post Data"}
		else:
			response_data = {}
			try:
				suggestion = Suggestion.objects.get(id=for_suggestion)
			except ObjectDoesNotExist:
				response_data = {"ERROR": "Invalid Post Data"}
			else:
				with transaction.atomic():
					try:
						vote = SuggestionVote.objects.get(from_user=request.user, for_suggestion=suggestion)
					except ObjectDoesNotExist:
						vote_diffrence = vote_data
						vote = SuggestionVote.objects.create(from_user=request.user, for_suggestion=suggestion, value=vote_data)
					else:
						vote_diffrence = vote_data*-1 if vote.value == vote_data else vote_data*2
						if vote.value == vote_data:
							vote.delete()
						else:
							vote.time=timezone.now()
							vote.value=vote_data
							vote.save()

				response_data['result'] = 'OK'

				response_data['vote_data'] = vote_diffrence
				response_data['for_suggestion'] = for_suggestion
	else:
		response_data = {"ERROR": "No Post Data"}

	return HttpResponse(
		json.dumps(response_data),
		content_type="application/json"
	)

	# how to implement on index: https://realpython.com/blog/python/django-and-ajax-form-submissions/

community/suggestions/templates/suggestions/add.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% load bootstrap %}

{% block title %}Add Suggestion{% endblock %}

{% block beforebody %}
    <style type="text/css">
        .item-tag > span::before { 
            content: "[";
        }
        .item-tag > span::after { 
            content: "]";
        }
    </style>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <div class="btn-group btn-breadcrumb">
            <a href="{% url 'suggestions:index' %}"><i class="fa fa-folder-open" aria-hidden="true"></i> {% trans "Suggestions" %}</a>
            <a href="{{ request.get_full_path }}" class="active">{% trans "Add Suggestion" %}</a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="well bs-component">

			<form class="form-horizontal" role="form" action="{{ form_url }}" id="form" method="post" enctype="multipart/form-data">
				<fieldset>
				    <legend>{% trans "New Suggestion" %}</legend>
				    {% csrf_token %}
				    {{ form|bootstrap_horizontal }}
				    <div class="form-group">
				        <div class="col-lg-10 col-lg-offset-2">
				            <a class="btn btn-warning" href="{{ back_url|default_if_none:"javascript:history.go(-1)" }}">{% trans "Go back" %}</a>
				            <button class="btn btn-default" type="reset">Cancel</button>
				            <input class="btn btn-primary" type="submit" name="AddPostForm" value="Submit">
				    	</div>
				    </div>
			    </fieldset>
			</form>
            
        </div>
    </div>
</div>
{% endblock %}

community/suggestions/templates/suggestions/filtered.html
{% extends 'base.html' %}
{% load cache %}
{% load i18n %}
{% load base_tags %}


{% block content %}

{% site_setting "SUGGESTIONS_ARCHIVED_VALUE" as status_archived %}

<style type="text/css">
	.item-tag > span::before { 
		content: "[";
	}
	.item-tag > span::after { 
		content: "]";
	}
</style>

<div class="row">
	<div class="col-sm-12">
		<div class="btn-group btn-breadcrumb">
	        <a href="{% url 'suggestions:index' %}"><i class="fa fa-home" aria-hidden="true"></i> {% trans "Suggestions" %}</a>
	        <a href="{{ request.get_full_path }}" class="active">{% trans "Filtered" %}</a>
	    </div>
    </div>
</div>

<div class="row">
	<div class="col-sm-12">
	  <div class="panel-group">
		<div class="panel panel-default">
			<div class="panel-heading">
    			<div class="row">
					<div class="col-sm-12">
						<div class="pull-right" style="padding-top: 8px;">
							<div class="btn-toolbar nomargin" role="toolbar">
								<div class="btn-group">
							        {% include 'util/paginator.html' with page=suggestions_page request=request only %}
							    </div>
							    <div class="btn-group pull-right">
                                    <div class="btn-toolbar nomargin" role="toolbar">
                                        <div class="btn-group pull-right">
                                            <a href="{% url 'suggestions:add_suggestion' %}" class="btn btn-default">{% trans "New Suggestion" %}</a>
                                            <div class="btn-group">
                                                <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                                    <i class="fa fa-caret-down" aria-hidden="true"></i>
                                                </a>
                                                <ul class="dropdown-menu dropdown-menu-right">
                                                	<li><a href="{% url 'suggestions:index' %}">Overview</a></li>
                                                    <li><a href="{% url 'suggestions:filtered_overview' %}?{% for cat in status_archived %}s={{ cat }}&amp;{% endfor %}">Archives</a></li>
                                                    <li><a href="#">Filter</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
									{% if moderator %}
									<div class="btn-group">
								    	<a href="#" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
								        	<i class="fa fa-caret-down" aria-hidden="true"></i>
								    	</a>
								    	<ul class="dropdown-menu dropdown-menu-right">
								      		<li class="dropdown-header">{% trans "Moderator control" %}</li>
								      		<li class="divider"></li>
								        	<li><a href="">{% trans "Delete multiple" %}</a></li>
								    	</ul>
								    </div>
								    {% endif %}	
							    </div>
							</div>
						</div>
						<h3>
							<strong>{% trans "Filtered Suggestions" %}</strong>
							<p><small>Suggestions that passed your filter.</small></p>
						</h3>
					</div>
				</div>
    		</div>
    	</div>
	    </div>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
	  <div class="panel-group">
		<div class="panel panel-default">
			<div class="panel-heading">
				Suggestions
			</div>
			<div class="panel-body" >
				{% for item in suggestions_page %}
					<div class="row" id="suggestion_{{ item.id }}">
						<div class="col-sm-12">
							<div style="float: left; width: 50px;height: 50px;position:relative">
								<h2 style="margin-top: 8px;text-align: right;margin-left: -10px;">{{ item.rating|default_if_none:'0' }}</h2>
					        </div>
					        <div style="float: left;border-right: 1px solid rgba(255,255,255, .1);height: 46px;width: 7px;margin-top:2px"></div>
							<div style="display: block; margin-left: 62px;min-height: 50px;">
									<strong><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></strong>
									<p><strong class="item-tag">{{ item.status.value_html|safe }}</strong>
										{% with item.categories.all as categories %}
											{% if categories %}
												<em>{% trans "Categories:" %}</em> 
													{% for ct in categories %}
														{% if forloop.last %}
															{{ ct }}.
														{% else %}
															{{ ct }},
														{% endif %}
													{% endfor %}
											{% endif %}
										{% endwith %}
									</p>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
			<div class="panel-footer"">
				<div class="row">
					<div class="col-sm-12">
						{% if user.is_authenticated %}
							<div class="pull-right">
								<a href="{% url 'suggestions:add_suggestion'%}" class="btn btn-default">{% trans "New Suggestion" %}</a>
							</div>
						{% endif %}
						<div class="pull-left">{% include 'util/paginator.html' with page=suggestions_page request=request only %}</div>
					</div>
				</div>
			</div>
		</div>
	    </div>
	</div>
</div>

{% endblock %}

community/suggestions/templates/suggestions/index.html
{% extends 'base.html' %}
{% load cache %}
{% load i18n %}
{% load base_tags %}


{% block content %}

{% site_setting "SUGGESTIONS_ARCHIVED_VALUE" as status_archived %}

<style type="text/css">
	.item-tag > span::before { 
		content: "[";
	}
	.item-tag > span::after { 
		content: "]";
	}
</style>

<div class="row">
	<div class="col-sm-12">
		<div class="btn-group btn-breadcrumb">
	        <a href="{% url 'suggestions:index' %}" class="active"><i class="fa fa-home" aria-hidden="true"></i> {% trans "Suggestions" %}</a>
	    </div>
    </div>
</div>

<div class="row">
	<div class="col-sm-12">
	  <div class="panel-group">
		<div class="panel panel-default">
			<div class="panel-heading">
    			<div class="row">
					<div class="col-sm-12">
						<div class="pull-right" style="padding-top: 8px;">
							<div class="btn-toolbar nomargin" role="toolbar">
								<div class="btn-group">
							        {% include 'util/paginator.html' with page=suggestions_page request=request only %}
							    </div>
							    <div class="btn-group pull-right">
                                    <div class="btn-toolbar nomargin" role="toolbar">
                                        <div class="btn-group pull-right">
                                            <a href="{% url 'suggestions:add_suggestion' %}" class="btn btn-default">{% trans "New Suggestion" %}</a>
                                            <div class="btn-group">
                                                <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                                    <i class="fa fa-caret-down" aria-hidden="true"></i>
                                                </a>
                                                <ul class="dropdown-menu dropdown-menu-right">
                                                	<li><a href="{% url 'suggestions:index' %}">Overview</a></li>
                                                    <li><a href="{% url 'suggestions:filtered_overview' %}?{% for cat in status_archived %}s={{ cat }}&amp;{% endfor %}">Archives</a></li>
                                                    <li><a href="#">Filter</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
									{% if moderator %}
									<div class="btn-group">
								    	<a href="#" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
								        	<i class="fa fa-caret-down" aria-hidden="true"></i>
								    	</a>
								    	<ul class="dropdown-menu dropdown-menu-right">
								      		<li class="dropdown-header">{% trans "Moderator control" %}</li>
								      		<li class="divider"></li>
								        	<li><a href="">{% trans "Delete multiple" %}</a></li>
								    	</ul>
								    </div>
								    {% endif %}	
							    </div>
							</div>
						</div>
						<h3>
							<strong>{% trans "Suggestions Overview" %}</strong>
							<p><small>A list of all suggestions for this community (needs more info!)</small></p>
						</h3>
					</div>
				</div>
    		</div>
    	</div>
	    </div>
	</div>
</div>

<div class="row">
	<div class="col-lg-7">
	  <div class="panel-group">
		<div class="panel panel-default">
			<div class="panel-heading">
				Suggestions
			</div>
			<div class="panel-body" >
				{% for item in suggestions_page %}
					<div class="row" id="suggestion_{{ item.id }}">
						<div class="col-sm-12">
							<div style="float: left; width: 50px;height: 50px;position:relative">
								<h2 style="margin-top: 8px;text-align: right;margin-left: -10px;">{{ item.rating|default_if_none:'0' }}</h2>
					        </div>
					        <div style="float: left;border-right: 1px solid rgba(255,255,255, .1);height: 46px;width: 7px;margin-top:2px"></div>
							<div style="display: block; margin-left: 62px;min-height: 50px;">
									<strong><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></strong>
									<p><strong class="item-tag">{{ item.status.value_html|safe }}</strong>
										{% with item.categories.all as categories %}
											{% if categories %}
												<em>{% trans "Categories:" %}</em> 
													{% for ct in categories %}
														{% if forloop.last %}
															{{ ct }}.
														{% else %}
															{{ ct }},
														{% endif %}
													{% endfor %}
											{% endif %}
										{% endwith %}
									</p>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
			<div class="panel-footer"">
				<div class="row">
					<div class="col-sm-12">
						{% if user.is_authenticated %}
							<div class="pull-right">
								<a href="{% url 'suggestions:add_suggestion'%}" class="btn btn-default">{% trans "New Suggestion" %}</a>
							</div>
						{% endif %}
						<div class="pull-left">{% include 'util/paginator.html' with page=suggestions_page request=request only %}</div>
					</div>
				</div>
			</div>
		</div>
	    </div>
	</div>

	<div class="col-lg-5">
		<div class="well">
			<p>Need help? Need an unban? Have a complaint? This is not the place to be!<br>See <a href="#">here</a> for more info.</p>

			<p>Here you can submit suggestions to improve anything to do with TU, the website, the community or anything it owns.</p>
			<p>You may also vote on which suggestions to implement, the more votes, the more likely and faster it will be implemented.</p>
			<p>Auggestions with a negative rating will likely not be implemented at all.</p>
		</div>
	</div>
</div>

{% endblock %}